services:
  traefik:
    image: traefik:v2.10
    container_name: traefik

    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Redirección automática HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # Solo file provider
      - "--providers.file.filename=/etc/traefik/dynamic.yml"

      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro

    networks:
      - proxy

  web:
    image: nginx:latest
    container_name: web

    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro

    networks:
      - proxy

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog

    ports:
      - "1025:1025"

    networks:
      - proxy

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer

    command: -H unix:///var/run/docker.sock

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    networks:
      - proxy

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: laboratorio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - proxy

  adminer:
    image: adminer:latest
    container_name: adminer

    networks:
      - proxy

  mysql:
    image: mysql:8
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wp123

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    networks:
      - proxy

  redis:
    image: redis:7-alpine
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - proxy

volumes:
  portainer_data:
  postgres_data:
  mysql_data:
  redis_data:

networks:
  proxy:
    driver: bridge
